#!/usr/bin/env python

import rospy

from comp0037_mapper.mapper_node import MapperNode

if __name__ == '__main__':

    try:
        counter = 0
        mapperNode = MapperNode()
        mapperNode.run()
        if counter == 0:
            mapperNode.recordEntropy()
            counter+=1
    except rospy.ROSInterruptException:
        pass
